[env]
_.python.venv = ".venv"

[tools]
prettier = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
uv = "latest"

[settings]
auto_install = true
experimental = true

[hooks]
enter = ["mise install"]
postinstall = ["scripts/mise-postinstall.sh"]
